name: Mise à jour des cours

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-cours:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: |
          pip install requests beautifulsoup4

      - name: Récupérer les cours
        env:
          MATHS_CPGE_ID: ${{ secrets.MATHS_CPGE_ID }}
          MATHS_CPGE_PASSWORD: ${{ secrets.MATHS_CPGE_PASSWORD }}
        run: |
          python scripts/update_cours.py

      - name: Enregistrer les changements
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add programmes/cours/

          if git diff --cached --quiet; then
            echo "Aucun changement."
          else
            git commit -m "Mise à jour des cours"
            git push
          fi